name: iOS Release

on:
  release:
    types:
      - published

  workflow_dispatch:

env:
  GITHUB_REF_NAME: ${{ github.event.release.tag_name }}

jobs:
  build-ios-app:
    name: Release App
    runs-on: macos-15

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js with GitHub Packages auth
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/

      - name: Cache npm cache directory
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # - name: Install npm dependencies
      #   run: npm ci

      - name: Update version
        run: npm version ${{ env.GITHUB_REF_NAME }} --no-git-tag-version

      - name: Commit version updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b chore/version-bump-${{env.GITHUB_REF_NAME}}
          git add package.json package-lock.json
          git commit -m "chore(version): bump app version ${{env.GITHUB_REF_NAME}}"
          git push -f -u --no-verify origin HEAD

      # - name: Create PR for version bump
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}
      #     branch: chore/version-bump-${{env.GITHUB_REF_NAME}}
      #     base: main
      #     title: "chore: bump version to ${{ env.GITHUB_REF_NAME }}"
      #     body: "Automated version bump from GitHub App"
      #     commit-message: "chore: bump version ${{ env.GITHUB_REF_NAME }}"
      
      # - name: Set PR number
      #   run: echo "PR_NUMBER=${{ steps.pr.outputs.pull-request-number }}" >> $GITHUB_ENV

      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          PR_URL=$(gh pr create --title "chore(version): bump app version ${{env.GITHUB_REF_NAME}}" --body "Update app version" --base main --head chore/version-bump-${{env.GITHUB_REF_NAME}})
          PR_NUMBER=$(echo "$PR_URL" | awk -F'/' '{print $NF}')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          gh pr review $PR_NUMBER --approve -b "Approving as admin"

      - name: Merge PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          pr_number=${{ env.PR_NUMBER }}
          gh pr merge $pr_number --auto --squash
